---
title: "MFA just NT"
output: html_document
date: "2025-12-10"
---




Just a NT model


```{r}

# justnNT
dta_vars_4mfa_2_wide_sel2
dta_vars_4mfa_2_wide_sel2_nt<- dta_vars_4mfa_2_wide_sel2%>%subset(as.numeric(as.character(dta_vars_4mfa_2_wide_sel2$ssid))<500)
dta_vars_4mfa_2_wide_sel2_nt2<- dta_vars_4mfa_2_wide_sel2%>%subset(as.numeric(as.character(dta_vars_4mfa_2_wide_sel2$ssid))>700)

dta_vars_4mfa_2_wide_sel2_nt<-bind_rows(dta_vars_4mfa_2_wide_sel2_nt,dta_vars_4mfa_2_wide_sel2_nt2)

colnames(dta_vars_4mfa_2_wide_sel2_nt)

```


```{r}
dta_vars_4mfa_2_wide_sel_complet_nt <- missMDA::imputeMFA(dta_vars_4mfa_2_wide_sel2_nt[,c(2:251)],
                                               ncp=2,
                                               group=c(50,50,50,50,50),
                                        type=c( "s","s","s","s","s"))


dta_vars_4mfa_2_wide_sel_complet_nt_obs<- dta_vars_4mfa_2_wide_sel_complet_nt$completeObs


# dta_vars_4mfa_2_wide_sel_complet2 <- missMDA::imputeMFA(dta_vars_4mfa_2_wide_sel2[,c(2:251)],
#                                                ncp=2,
#                                                group=c(50,50,50,50,50),
#                                         type=c( "s","s","s","s","s"))


# dta_vars_4mfa_2_wide_sel_complet2_obs<- dta_vars_4mfa_2_wide_sel_complet2$completeObs


mod_mfa$mfa_wide_nt<- FactoMineR::MFA(dta_vars_4mfa_2_wide_sel_complet_nt_obs,
             # tab.comp=dta_vars_4mfa_2_wide_sel_complet_obs,
              group=c(50,50,50,50,50),
             # type=c( "c","c","c","c","c"),
              type=c("s","s","s","s","s"),
             name.group=c( "valence","arousal","pupil","hr","scr"),
             ncp = 3,
             # num.group.sup=c(1,2),
             graph=TRUE)


```

```{r}



# require(factoextra)
fviz_contrib(mod_mfa$mfa_wide_nt, "quanti.var", axes = 1, top = 50)
fviz_contrib(mod_mfa$mfa_wide_nt, "quanti.var", axes = 2,top = 50)
fviz_contrib(mod_mfa$mfa_wide_nt, "quanti.var", axes = 3,top = 50)

# require(factoextra)
fviz_contrib(mod_mfa$mfa_wide_nt, "group", axes = 1, top = 50)
fviz_contrib(mod_mfa$mfa_wide_nt, "group", axes = 2,top = 50)
fviz_contrib(mod_mfa$mfa_wide_nt, "group", axes = 3,top = 50)



factoextra::fviz_mfa_group(mod_mfa$mfa_wide_nt)
factoextra::fviz_mfa_group(mod_mfa$mfa_wide_nt, axes = c(1,3))
factoextra::fviz_mfa_group(mod_mfa$mfa_wide_nt, axes = c(2,3))


```

```{r}
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_coord_1<- mod_mfa$mfa_wide_nt$ind$coord[,1]
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_coord_2<- mod_mfa$mfa_wide_nt$ind$coord[,2]
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_coord_3<- mod_mfa$mfa_wide_nt$ind$coord[,3]

dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_cos2_1<- mod_mfa$mfa_wide_nt$ind$cos2[,1]
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_cos2_2<- mod_mfa$mfa_wide_nt$ind$cos2[,2]
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_cos2_3<- mod_mfa$mfa_wide_nt$ind$cos2[,3]

dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_contrib_1<- mod_mfa$mfa_wide_nt$ind$contrib[,1]
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_contrib_2<- mod_mfa$mfa_wide_nt$ind$contrib[,2]
dta_vars_4mfa_2_wide_sel2_nt$mfa_z_sid_contrib_3<- mod_mfa$mfa_wide_nt$ind$contrib[,3]
```


```{r}
dta_vars_4mfa_2_wide_sel

colnames(dta_4_mfa)

# dta_ssid_agg_quest<- dta_4_mfa%>%
#   group_by(ssid,asd_sid)%>%
#   summarise_at(c("age", "tas","aq","tas_imptd_z", "aq_imptd_z"), mean, na.rm = T)

dta_vars_4mfa_2_wide_sel2_nt<- dta_vars_4mfa_2_wide_sel2_nt%>%
left_join(dta_ssid_agg_quest)


# dta_vars_4mfa_2_wide_sel$control_asd<- if_else(dta_vars_4mfa_2_wide_sel$asd_sid == "ASD", "ASD", "CONTROL")

```

```{r}
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(aq,mfa_z_sid_coord_1))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(aq,mfa_z_sid_coord_2))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(aq,mfa_z_sid_coord_3))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()


dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(tas,mfa_z_sid_coord_1))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(tas,mfa_z_sid_coord_2))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(tas,mfa_z_sid_coord_3))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()


```




```{r}

# contrib
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(aq,mfa_z_sid_contrib_1))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(aq,log1p(mfa_z_sid_contrib_2+.1)))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(aq,mfa_z_sid_contrib_3))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()


dta_vars_4mfa_2_wide_sel2_nt%>%

  ggplot(aes(tas,mfa_z_sid_contrib_1))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%
    subset(tas<65)%>%

  ggplot(aes(tas,log1p(mfa_z_sid_contrib_2+.1)))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
dta_vars_4mfa_2_wide_sel2_nt%>%


  ggplot(aes(tas,mfa_z_sid_contrib_3))+
  geom_point()+
  geom_smooth(method = "lm")+
    ggpubr::stat_cor()
```


